name: swit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.37
  firebase_core: ^3.3.0
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  freezed: ^2.5.7


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - .env

  fonts:
    - family: cafe24OhsquareAir
      fonts:
        - asset: assets/fonts/cafe24_ohsquare_air.ttf
    - family: GmarketSansTTFLight
      fonts:
        - asset: assets/fonts/GmarketSansTTFLight.ttf
    - family: GmarketSansTTFMedium
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf