name: swit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.37
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/audios/
    - assets/icons/

  fonts:
    - family: cafe24OhsquareAir
      fonts:
        - asset: assets/fonts/cafe24_ohsquare_air.ttf
    - family: GmarketSansTTFLight
      fonts:
        - asset: assets/fonts/GmarketSansTTFLight.ttf
    - family: GmarketSansTTFMedium
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf